---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/


---
spring.config.activate.on-profile: team-1
words: Шахтар,Дніпро-1

---
spring.config.activate.on-profile: team-2
words: ДинамоКиїв,Рух 

---
spring.config.activate.on-profile: team-3
words: Зоря,Олександрія

---
spring.config.activate.on-profile: team-4
words: Колос,Металіст1925

---
spring.config.activate.on-profile: team-5
words: Ворскла,ДинамоКиїв
